version: "3"

services:
  web:
    image: red
    build: .
    container_name: red_web
    expose:
      - "8000:8000"
    volumes:
      - .:/usr/src/app:z
  nginx:
    image: nginx
    container_name: nginx
    volume:
      - nginx.conf : /etc/nginx/nginx.conf
      - location.d/location.conf : /etc/nginx/location.d/location.conf
    expose:
      - "80:80"
    depends_on:
      - web
