version: "3"

services:
  green_web:
    image: green
    build: .
    container_name: green_web
    expose:
      - "8010"
    volumes:
      - .:/usr/src/app:z
  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/location/location.conf:/etc/nginx/location.d/location.conf
    ports:
      - "8000:80"
    depends_on:
      - green_web
