version: "3"

services:
  red_web:
    image: red
    build: .
    container_name: red_web
    expose:
      - "8000"
    volumes:
      - .:/usr/src/app:z
  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/location/location.conf:/etc/nginx/location.d/location.conf
    ports:
      - "8000:80"
    depends_on:
      - red_web
